name: Update Scripts
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: take
        run: bash script-get.sh

      - name: Generate date 
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Commit filters
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: '*.js'
          default_author: github_actor 
          message: 'Cập nhật script: ${{ env.DATE }}'
          push: true
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1

